#!/bin/bash -x

pushd build
[ ! -d u-boot ]       && git clone git://git.denx.de/u-boot.git
[ ! -d sunxi-boards ] && git clone git://github.com/linux-sunxi/sunxi-boards.git
[ ! -d linux-sunxi ]  &&git clone git://github.com/linux-sunxi/linux-sunxi.git -b sunxi-next

export ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
# build u-boot for  Orange PI Plus
pushd u-boot
make orangepi_plus_defconfig
make -j`nproc`
popd

# remove target
rm -rf /build/output
mkdir -p /build/output/boot
# build kernel
pushd linux-sunxi
make sunxi_defconfig
make -j`nproc` zImage dtbs
make -j`nproc` modules
INSTALL_MOD_PATH=/build/output make modules_install
cp arch/arm/boot/zImage /build/output/boot
cp arch/arm/boot/dts/sun8i-h3-orangepi-plus.dts /build/output/boot
popd
# Image
cd /build
[ ! -f /build/ArchLinuxARM-armv7-latest.tar.gz ] && wget http://archlinuxarm.org/os/ArchLinuxARM-armv7-latest.tar.gz
pushd output
mkdir usr
mv lib usr
tar zxf /build/ArchLinuxARM-armv7-latest.tar.gz
rm -rf usr/lib/modules/4.4.3-1-ARCH usr/lib/modules/extramodules-4.4--armv7
popd ; popd
exit 0
